apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  ports:
  - port: 80              
    targetPort: 5000
    nodePort: 30080       
  selector:
    run: server   
